### ISSUE TITLE
on running the train.py comes KeyError: 'vb'? how to solve this?

### ISSUE THREAD

**Issue by txchen-USTC** [JuliaWolleb/Diffusion-based-Segmentation#2]
Setting up a new session...
Setting up a new session...
Setting up a new session...
Logging to ./results
creating model and diffusion...
creating data loader...
training...
Traceback (most recent call last):
  File "scripts/segmentation_train.py", line 89, in <module>
    main()
  File "scripts/segmentation_train.py", line 62, in main
    lr_anneal_steps=args.lr_anneal_steps,
  File "./guided_diffusion/train_util.py", line 189, in run_loop
    self.run_step(batch, cond)
  File "./guided_diffusion/train_util.py", line 214, in run_step
    lossseg, losscls, lossrec, sample = self.forward_backward(batch, cond)
  File "./guided_diffusion/train_util.py", line 260, in forward_backward
    losscls = (losses["vb"] * weights).mean().detach()
KeyError: 'vb'

**Comment by JuliaWolleb** [comment]
Hi
Have you set the flat `--learn_sigma True `?
Then, losses["vb"] should not give any key error.

**Comment by long-island-ice-tea** [comment]
do you have a pretrained model on BRATS2020?

**Comment by MuqinZ** [comment]
Can you give me your E-mail. I want to talk about this Net-Model with you.
