### ISSUE TITLE
Hello, why is this question?

### ISSUE THREAD

**Issue by zjtggssg** [JuliaWolleb/Diffusion-based-Segmentation#5]
I'm running the source code and I have this problem, there is no good solution, I hope I can answer my doubts, thanks.
`Traceback (most recent call last):
  File "/home/ws/Desktop/Diffusion-based-Segmentation-main/guided_diffusion/train_util.py", line 179, in run_loop
    batch, cond = next(data_iter)
  File "/home/ws/.conda/envs/unet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/ws/.conda/envs/unet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 556, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "/home/ws/.conda/envs/unet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 508, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
StopIteration `

**Comment by JuliaWolleb** [comment]
Hi
Does your script stop due to this StopIteration error? 
If not, you are fine. If yes, you need to adapt your data loader not to stop once it loaded all images of the training set.

**Comment by JuliaWolleb** [comment]
yes, you need to adapt the file _bratsloader.py_ to your dataset, or store the data as indicated in the folder _/data_.

**Comment by zjtggssg** [comment]
But what I am using is . /data/training that you provided.

**Comment by JuliaWolleb** [comment]
could you give me the detailed error message? where does this error occur?

**Comment by zjtggssg** [comment]
`Traceback (most recent call last):
  File "/home/ws/Desktop/Diffusion-based-Segmentation-main/guided_diffusion/train_util.py", line 179, in run_loop
    batch, cond = next(data_iter)
  File "/home/ws/.conda/envs/unet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/ws/.conda/envs/unet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 556, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "/home/ws/.conda/envs/unet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 508, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ws/Desktop/Diffusion-based-Segmentation-main/scripts/segmentation_train.py", line 90, in <module>
    main()
  File "/home/ws/Desktop/Diffusion-based-Segmentation-main/scripts/segmentation_train.py", line 63, in main
    lr_anneal_steps=args.lr_anneal_steps,
  File "/home/ws/Desktop/Diffusion-based-Segmentation-main/guided_diffusion/train_util.py", line 184, in run_loop
    batch, cond = next(data_iter)
  File "/home/ws/.conda/envs/unet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/ws/.conda/envs/unet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 556, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "/home/ws/.conda/envs/unet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 508, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
StopIteration`    This is the running error message。
and then I set the breakpoint `data = self._next_data()`，It came up with this error `{AttributeError}'_SingleProcessDataLoaderIter' object has no attribute 'seqtypes_set'`

**Comment by JuliaWolleb** [comment]
Can you print the length of your BRATS dataset in the script _segmentation_train.py_?

**Comment by zjtggssg** [comment]
Hi, I am printing out a length of 0, which means that I am not getting the file in the dataset.

**Comment by zjtggssg** [comment]
Hi, I am printing out a length of 0, which means that I am not getting the file in the dataset.

**Comment by JuliaWolleb** [comment]
ok, did you set all paths to the dataset correctly?  The error message happens because your data loader cannot find any files in the dataset.

**Comment by zjtggssg** [comment]
I tried to set the absolute path, but I can't read the data I want.

**Comment by zjtggssg** [comment]
I don't seem to be able to get into the loop to read the file`        for root, dirs, files in os.walk(self.directory):
            # if there are no subdirs, we have data
            # print("root: ",root)
            print(1)
            if not dirs:
                files.sort()
                datapoint = dict()
                # extract all files as channels
                for f in files:
                    seqtype = f.split('_')[3]
                    datapoint[seqtype] = os.path.join(root, f)
                assert set(datapoint.keys()) == self.seqtypes_set, \
                    f'datapoint is incomplete, keys are {datapoint.keys()}'
                self.database.append(datapoint)`
