### ISSUE TITLE
Input Channel Settings

### ISSUE THREAD

**Issue by popleyi** [JuliaWolleb/Diffusion-based-Segmentation#6]
Thanks for sharing the code. 

I tried to apply the source code on my own dataset. I changed the data loader following the BRATS example to have one channel as the input and the segmentation as the second channel. Then I changed the "in_channels=5" to "in_channels=2" for the UNetModel. However, it shows the error that the expected input channel should be 3. 

In addition, gaussian_diffusion.py file, the it has been set to img.shape != (1, 5, 224, 224). what's this mean?

Any suggestions will be much appreciated. Thanks!

**Comment by JuliaWolleb** [comment]
Where did you change "in_channels=2"? In the file _script_util.py?_ Then it should work with a 2-channel input. 
Could you show me the detailed error message?

As for the second point, this means that if your image is already of the shape [conditional image, segmentation mask at time t], then you skip this step. Otherwise, you need to concatenate the original input image with the segmentation mask at time t. In your case, you would need to change this line to:
img.shape != (1, 2, image_height, image_width)

**Comment by popleyi** [comment]
Thanks for your reply. 

I can confirm that the output shape from the dataloader is _torch.Size([2, 256, 256])_

In the _script_util.py_ file, I modified the _in_channels_ for the _UNetModel_ to 2, which shown in below.

return UNetModel(
        image_size=image_size,
        in_channels=2,
        model_channels=num_channels,
        out_channels=2,#(3 if not learn_sigma else 6),
        num_res_blocks=num_res_blocks,
        attention_resolutions=tuple(attention_ds),
        dropout=dropout,
        channel_mult=channel_mult,
        num_classes=(NUM_CLASSES if class_cond else None),
        use_checkpoint=use_checkpoint,
        use_fp16=use_fp16,
        num_heads=num_heads,
        num_head_channels=num_head_channels,
        num_heads_upsample=num_heads_upsample,
        use_scale_shift_norm=use_scale_shift_norm,
        resblock_updown=resblock_updown,
        use_new_attention_order=use_new_attention_order,
    )

As suggested, I have modified the _gaussian_diffusion.py_ file to img.shape != (1, 2, image_height, image_width)

the error message is like the followings.

creating model and diffusion...
creating data loader...
training...
torch.Size([2, 256, 256])
torch.Size([2, 256, 256])
torch.Size([2, 256, 256])
torch.Size([2, 256, 256])
torch.Size([2, 256, 256])
torch.Size([2, 256, 256])
torch.Size([2, 256, 256])
torch.Size([2, 256, 256])
Traceback (most recent call last):
  File "/home/anaconda3/envs/py36/lib/python3.6/pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "/home/anaconda3/envs/py36/lib/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "/home/anaconda3/envs/py36/lib/python3.6/bdb.py", line 434, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/mnt/Research/Diffusion-based-Segmentation/scripts/segmentation_train.py", line 3, in <module>
    """
  File "/mnt/Research/Diffusion-based-Segmentation/scripts/segmentation_train.py", line 65, in main
    lr_anneal_steps=args.lr_anneal_steps,
  File "/mnt/Research/Diffusion-based-Segmentation/guided_diffusion/train_util.py", line 186, in run_loop
    self.run_step(batch, cond)
  File "/mnt/Research/Diffusion-based-Segmentation/guided_diffusion/train_util.py", line 207, in run_step
    sample = self.forward_backward(batch, cond)
  File "/mnt/Research/Diffusion-based-Segmentation/guided_diffusion/train_util.py", line 238, in forward_backward
    losses1 = compute_losses()
  File "/mnt/Research/Diffusion-based-Segmentation/guided_diffusion/gaussian_diffusion.py", line 937, in training_losses_segmentation
    model_output = model(x_t, self._scale_timesteps(t), **model_kwargs)
  File "/home/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/Research/Diffusion-based-Segmentation/guided_diffusion/unet.py", line 657, in forward
    h = module(h, emb)
  File "/home/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/Research/Diffusion-based-Segmentation/guided_diffusion/unet.py", line 74, in forward
    x = layer(x)
  File "/home/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 443, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 440, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [128, 2, 3, 3], expected input[8, 3, 256, 256] to have 2 channels, but got 3 channels instead
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program


Thanks for your help!
