### ISSUE TITLE
testing error

### ISSUE THREAD

**Issue by lanlinxxs** [JuliaWolleb/Diffusion-based-Segmentation#68]
Hello, I encountered an error during prediction. Can you tell me why this happened?
Traceback (most recent call last):
  File "/root/autodl-tmp/scripts/segmentation_sample.py", line 130, in <module>
    main()
  File "/root/autodl-tmp/scripts/segmentation_sample.py", line 97, in main
    sample, x_noisy, org = sample_fn(
  File "/root/autodl-tmp/guided_diffusion/gaussian_diffusion.py", line 520, in p_sample_loop_known
    for sample in self.p_sample_loop_progressive(
  File "/root/autodl-tmp/guided_diffusion/gaussian_diffusion.py", line 586, in p_sample_loop_progressive
    out = self.p_sample(
  File "/root/autodl-tmp/guided_diffusion/gaussian_diffusion.py", line 433, in p_sample
    out = self.p_mean_variance(
  File "/root/autodl-tmp/guided_diffusion/respace.py", line 96, in p_mean_variance
    return super().p_mean_variance(self._wrap_model(model), *args, **kwargs)
  File "/root/autodl-tmp/guided_diffusion/gaussian_diffusion.py", line 316, in p_mean_variance
    self._predict_xstart_from_eps(x_t=x, t=t, eps=model_output)
  File "/root/autodl-tmp/guided_diffusion/gaussian_diffusion.py", line 337, in _predict_xstart_from_eps
    assert x_t.shape == eps.shape
AssertionError

**Comment by wildailurpodan** [comment]
x_t shape: torch.Size([1, 1, 224, 224])
eps shape: torch.Size([1, 2, 224, 224])
 i met the same error as you do. It looks like the expected output has two layers, is the original and the generated mask put together? Grayscale images should have only one layer

**Comment by Hang3Y** [comment]
> x_t 形状：torch.Size([1, 1, 224, 224]) eps 形状：torch.Size([1, 2, 224, 224]) 我遇到了和你一样的错误。看起来预期的输出有两层，原始图像和生成的 mask 是放在一起的吗？灰度图像应该只有一层

I have the same issue. I tried to output the shape just like yours. Could you please share how you managed to solve it?
