### ISSUE TITLE
I ran into a problem when running segmentation_sample.py.

### ISSUE THREAD

**Issue by jaceqin** [JuliaWolleb/Diffusion-based-Segmentation#9]
Traceback (most recent call last):
  File "scripts/segmentation_sample.py", line 125, in <module>
    main()
  File "scripts/segmentation_sample.py", line 97, in main
    model_kwargs=model_kwargs,
  File "./guided_diffusion/gaussian_diffusion.py", line 524, in p_sample_loop_known
    progress=progress,
  File "./guided_diffusion/gaussian_diffusion.py", line 586, in p_sample_loop_progressive
    model_kwargs=model_kwargs,
  File "./guided_diffusion/gaussian_diffusion.py", line 433, in p_sample
    model_kwargs=model_kwargs,
  File "./guided_diffusion/respace.py", line 90, in p_mean_variance
    return super().p_mean_variance(self._wrap_model(model), *args, **kwargs)
  File "./guided_diffusion/gaussian_diffusion.py", line 310, in p_mean_variance
    self._predict_xstart_from_eps(x_t=x, t=t, eps=model_output)
  File "./guided_diffusion/gaussian_diffusion.py", line 331, in _predict_xstart_from_eps
    assert x_t.shape == eps.shape
AssertionError

**Comment by Rengongzhineng1999zxwang** [comment]
我也遇到这个问题，加我qq1194587948交流一下如何？

**Comment by JuliaWolleb** [comment]
Could you print _x_t.shape_ and _eps.shape_ in the indicated line?

**Comment by jaceqin** [comment]
eps.shape=torch.Size([1, 2, 224, 224])；x_t.shape=torch.Size([1, 1, 224, 224])

**Comment by jaceqin** [comment]
Do you know why eps.shape and x_t.shape are differen？I use your data and code.

**Comment by JuliaWolleb** [comment]
what is your "learn_sigma" flag? did you set it to `True` or `False`?

**Comment by jaceqin** [comment]
learn_sigma is False

**Comment by JuliaWolleb** [comment]
ok, try to set all flags according to the README file. There, we have `learn_sigma=True`

**Comment by jaceqin** [comment]
OK.Thank you!

**Comment by jaceqin** [comment]
我已经解决了

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年10月28日 13:53
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [JuliaWolleb/Diffusion-based-Segmentation] I ran into a problem when running segmentation_sample.py. (Issue #9)


我也遇到这个问题，加我qq1194587948交流一下如何？

―
